SELECT * FROM players;
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Tom Waits');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Billy Bob');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Kat Persone');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Burt Backrack');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Himme Lows');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'William Jones') ;
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Estabon Sanchez');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Brad Hudson');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Pede Bull');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Steve Bierb');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Michael Pers');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Maureen Ryan');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Lisa Moras');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Angelica Gertchez');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Donald Trump');
INSERT INTO PLAYERS (id, name) VALUES (DEFAULT, 'Rex Tillerson');
SELECT * FROM players;
