SELECT * FROM match; 
INSERT INTO match (match, winner_id, loser_id) VALUES (1,1,2);
INSERT INTO match (match, winner_id, loser_id) VALUES (2,3,4);
INSERT INTO match (match, winner_id, loser_id) VALUES (3,5,6);
INSERT INTO match (match, winner_id, loser_id) VALUES (4,7,8);
INSERT INTO match (match, winner_id, loser_id) VALUES (5,9,10);
INSERT INTO match (match, winner_id, loser_id) VALUES (6,11,12);
INSERT INTO match (match, winner_id, loser_id) VALUES (7,13,14);
INSERT INTO match (match, winner_id, loser_id) VALUES (8,15,16);
SELECT * FROM match;
